### PR TITLE
Add Jenkinsfile for scc merge

### PR DESCRIPTION
**Pull request by manics**
Similar to https://github.com/ome/omero-build/pull/9

Note this particular repo won't work unless https://github.com/ome/build-infra/issues/2 is fixed

### CODE REVIEW

**Comment by joshmoore** [comment]
build-infra branch no longer exists. Updating.

**Comment by joshmoore** [comment]
```
groovy.lang.MissingPropertyException: No such property: MERGE_GIT_USER for class: groovy.lang.Binding
```

@manics : currently you have this environment variable commented out? How were you intending for this to work? Is it possible to have this default to something so as to not require another setup step in the devspace README?

**Comment by manics** [comment]
See https://github.com/ome/omero-build/pull/9/files#diff-67aa146c8e78fa90df46bf5c5d40bf14R39

Since this PR was blocked on https://github.com/ome/build-infra/issues/2 I havne't kept it up to date

**Comment by joshmoore** [comment]
Green build testing on "south" :+1:

**Pull request merged**
