### PR TITLE
jenkins

### PR DESCRIPTION
**Pull request by jburel**
set the values of the plugins

cc @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
Makes sense. :+1: The only other option I can think of (as the plugins stabilize) is to require a PR bumping to `-SNAPSHOT` which should pick up the most recent build from nexus. But I haven't tested that in a while, so if this is working for you (and Trigger is happy), let's go for it.

**Comment by jburel** [comment]
Build failed to push to nexus
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-build/39/
the version file is updated.
The ice plugins value is not set in the file
It looks like a change to build-infra is required

**Comment by joshmoore** [comment]
That may be related to https://trello.com/c/AoDOspk2/106-provide-defaults-for-publishing-url-etc, i.e. differences in how the plugins and how the components are deployed.

**Comment by joshmoore** [comment]
This is now needed to get latest passing: https://latest-ci.openmicroscopy.org/jenkins/job/OMERO-build-push/12/console

Merging.

**Pull request merged**
